# Generated by Django 3.1 on 2020-09-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everydaycodings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('short_desc', models.TextField(max_length=90, verbose_name='Short Description')),
                ('desc', models.TextField(verbose_name='Description')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
            ],
        ),
    ]
