# Generated by Django 3.1 on 2020-09-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everydaycodings', '0004_auto_20200908_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
