# Generated by Django 3.1 on 2020-09-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everydaycodings', '0006_project_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='item',
        ),
    ]
